let folders = {
	steve: {
		lastSelected: '',
		name: 'steve',
		timesSelected: '',
		dateCreated: '',
		notes:'',
		background: '',
		folders: {
			general: {},
			focus: {
				name: 'focus',
				dateCreated: '',
				lastSelected: '',
				timesSelected: '',
				background: '',
				folders: '',
				notes: {
					'flicker jabs': {
						dateCreated: '',
						lastSelected: '',
						timesSelected: '',
						title: 'flicker jabs',
						text: 'Add more flicker jabs, flicker jabs to mishimas work well',
						images: '',
						video: '',
						background: '',
					},
					'rocket launcher': {
						dateCreated: '',
						lastSelected: '',
						timesSelected: '',
						title: 'rocket launcher',
						text:
							'rocket launcher is steves best option at the wall. Splats on hit',
						images: '',
						video: '',
						background: '',
					},
				},
			},
			topMoves: '',
			combinations: '',
			vs: {
				name: 'vs',
				dateCreated: '',
				lastSelected: '',
				timesSelected: '',
				background: '',
				folders: {
					paul: '',
					bryan: '',
					jin: {
						name: 'jin',
						dateCreated: '',
						lastSelected: '',
						timesSelected: '',
						folders: {},
						background: '',
						notes: {
							zen: {
								dateCreated: '',
								lastSelected: '',
								timesSelected: '',
								title: 'zen',
								text:
									'jin, from zen, go do either a mid or a low. The low is high crushing',
								images: '',
								video: '',
								background: '',
							},
							'12 frame wall bounce': {
								dateCreated: '',
								lastSelected: '',
								timesSelected: '',
								title: 'wall bounce',
								text: 'has a 12 frame? punisher, that wall bounces',
								images: '',
								video: '',
								background: '',
							},
						},
					},
				},
			},
		},
	},
	paul: {
		lastSelected: '',
		name: 'paul',
		timesSelected: '',
		dateCreated: '',
		background: '',
		folders: {
			general: {},
			focus: {
				name: 'focus',
				dateCreated: '',
				lastSelected: '',
				timesSelected: '',
				background: '',
				folders: '',
				notes: {
					df1: {
						dateCreated: '',
						lastSelected: '',
						timesSelected: '',
						title: 'df1',
						text: 'paul has a variety of options from df1',
						images: '',
						video: '',
						background: '',
					},
					'qcf3+4': {
						dateCreated: '',
						lastSelected: '',
						timesSelected: '',
						title: 'qcf3',
						text:
							'get your opponent ducking by using qcf3, then launch by using qcf 3+4',
						images: '',
						video: '',
						background: '',
					},
				},
			},
			topMoves: '',
			combinations: '',
			vs: {
				name: 'vs',
				dateCreated: '',
				lastSelected: '',
				timesSelected: '',
				background: '',
				folders: {
					paul: '',
					bryan: '',
					jin: {
						name: 'jin',
						dateCreated: '',
						lastSelected: '',
						timesSelected: '',
						folders: {},
						background: '',
						notes: {
							zen: {
								dateCreated: '',
								lastSelected: '',
								timesSelected: '',
								title: 'zen',
								text:
									'launch jins zen using df2, will still hit when using low crush',
								images: '',
								video: '',
								background: '',
							},
							'12 frame wall bounce': {
								dateCreated: '',
								lastSelected: '',
								timesSelected: '',
								title: 'wall bounce',
								text: 'punish with b1,2',
								images: '',
								video: '',
								background: '',
							},
						},
					},
				},
			},
		},

	},
}

export default folders
